// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/options.proto

package net.moznion.protoc.plugin.dynamodb;

public final class OptionsProto {
  private OptionsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(net.moznion.protoc.plugin.dynamodb.OptionsProto.fileopt);
    registry.add(net.moznion.protoc.plugin.dynamodb.OptionsProto.fieldopt);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.moznion.protoc.plugin.dynamodb.FileOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string java_dynamodb_table_name = 1;</code>
     * @return The javaDynamodbTableName.
     */
    java.lang.String getJavaDynamodbTableName();
    /**
     * <code>string java_dynamodb_table_name = 1;</code>
     * @return The bytes for javaDynamodbTableName.
     */
    com.google.protobuf.ByteString
        getJavaDynamodbTableNameBytes();
  }
  /**
   * Protobuf type {@code net.moznion.protoc.plugin.dynamodb.FileOptions}
   */
  public static final class FileOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.moznion.protoc.plugin.dynamodb.FileOptions)
      FileOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileOptions.newBuilder() to construct.
    private FileOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileOptions() {
      javaDynamodbTableName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileOptions();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              javaDynamodbTableName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.moznion.protoc.plugin.dynamodb.OptionsProto.internal_static_net_moznion_protoc_plugin_dynamodb_FileOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.moznion.protoc.plugin.dynamodb.OptionsProto.internal_static_net_moznion_protoc_plugin_dynamodb_FileOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions.class, net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions.Builder.class);
    }

    public static final int JAVA_DYNAMODB_TABLE_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object javaDynamodbTableName_;
    /**
     * <code>string java_dynamodb_table_name = 1;</code>
     * @return The javaDynamodbTableName.
     */
    @java.lang.Override
    public java.lang.String getJavaDynamodbTableName() {
      java.lang.Object ref = javaDynamodbTableName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        javaDynamodbTableName_ = s;
        return s;
      }
    }
    /**
     * <code>string java_dynamodb_table_name = 1;</code>
     * @return The bytes for javaDynamodbTableName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJavaDynamodbTableNameBytes() {
      java.lang.Object ref = javaDynamodbTableName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        javaDynamodbTableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(javaDynamodbTableName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, javaDynamodbTableName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(javaDynamodbTableName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, javaDynamodbTableName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions)) {
        return super.equals(obj);
      }
      net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions other = (net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions) obj;

      if (!getJavaDynamodbTableName()
          .equals(other.getJavaDynamodbTableName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JAVA_DYNAMODB_TABLE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getJavaDynamodbTableName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.moznion.protoc.plugin.dynamodb.FileOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.moznion.protoc.plugin.dynamodb.FileOptions)
        net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.moznion.protoc.plugin.dynamodb.OptionsProto.internal_static_net_moznion_protoc_plugin_dynamodb_FileOptions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.moznion.protoc.plugin.dynamodb.OptionsProto.internal_static_net_moznion_protoc_plugin_dynamodb_FileOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions.class, net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions.Builder.class);
      }

      // Construct using net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        javaDynamodbTableName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.moznion.protoc.plugin.dynamodb.OptionsProto.internal_static_net_moznion_protoc_plugin_dynamodb_FileOptions_descriptor;
      }

      @java.lang.Override
      public net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions getDefaultInstanceForType() {
        return net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions.getDefaultInstance();
      }

      @java.lang.Override
      public net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions build() {
        net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions buildPartial() {
        net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions result = new net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions(this);
        result.javaDynamodbTableName_ = javaDynamodbTableName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions) {
          return mergeFrom((net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions other) {
        if (other == net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions.getDefaultInstance()) return this;
        if (!other.getJavaDynamodbTableName().isEmpty()) {
          javaDynamodbTableName_ = other.javaDynamodbTableName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object javaDynamodbTableName_ = "";
      /**
       * <code>string java_dynamodb_table_name = 1;</code>
       * @return The javaDynamodbTableName.
       */
      public java.lang.String getJavaDynamodbTableName() {
        java.lang.Object ref = javaDynamodbTableName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          javaDynamodbTableName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string java_dynamodb_table_name = 1;</code>
       * @return The bytes for javaDynamodbTableName.
       */
      public com.google.protobuf.ByteString
          getJavaDynamodbTableNameBytes() {
        java.lang.Object ref = javaDynamodbTableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          javaDynamodbTableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string java_dynamodb_table_name = 1;</code>
       * @param value The javaDynamodbTableName to set.
       * @return This builder for chaining.
       */
      public Builder setJavaDynamodbTableName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        javaDynamodbTableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string java_dynamodb_table_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearJavaDynamodbTableName() {
        
        javaDynamodbTableName_ = getDefaultInstance().getJavaDynamodbTableName();
        onChanged();
        return this;
      }
      /**
       * <code>string java_dynamodb_table_name = 1;</code>
       * @param value The bytes for javaDynamodbTableName to set.
       * @return This builder for chaining.
       */
      public Builder setJavaDynamodbTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        javaDynamodbTableName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.moznion.protoc.plugin.dynamodb.FileOptions)
    }

    // @@protoc_insertion_point(class_scope:net.moznion.protoc.plugin.dynamodb.FileOptions)
    private static final net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions();
    }

    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileOptions>
        PARSER = new com.google.protobuf.AbstractParser<FileOptions>() {
      @java.lang.Override
      public FileOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileOptions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FieldOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.moznion.protoc.plugin.dynamodb.FieldOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool java_dynamodb_hash_key = 1;</code>
     * @return The javaDynamodbHashKey.
     */
    boolean getJavaDynamodbHashKey();

    /**
     * <code>bool java_dynamodb_range_key = 2;</code>
     * @return The javaDynamodbRangeKey.
     */
    boolean getJavaDynamodbRangeKey();

    /**
     * <code>bool java_dynamodb_ignore = 3;</code>
     * @return The javaDynamodbIgnore.
     */
    boolean getJavaDynamodbIgnore();

    /**
     * <code>string java_dynamodb_alias = 4;</code>
     * @return The javaDynamodbAlias.
     */
    java.lang.String getJavaDynamodbAlias();
    /**
     * <code>string java_dynamodb_alias = 4;</code>
     * @return The bytes for javaDynamodbAlias.
     */
    com.google.protobuf.ByteString
        getJavaDynamodbAliasBytes();

    /**
     * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
     * @return A list containing the javaDynamodbHashKeyGsiNames.
     */
    java.util.List<java.lang.String>
        getJavaDynamodbHashKeyGsiNamesList();
    /**
     * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
     * @return The count of javaDynamodbHashKeyGsiNames.
     */
    int getJavaDynamodbHashKeyGsiNamesCount();
    /**
     * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
     * @param index The index of the element to return.
     * @return The javaDynamodbHashKeyGsiNames at the given index.
     */
    java.lang.String getJavaDynamodbHashKeyGsiNames(int index);
    /**
     * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the javaDynamodbHashKeyGsiNames at the given index.
     */
    com.google.protobuf.ByteString
        getJavaDynamodbHashKeyGsiNamesBytes(int index);

    /**
     * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
     * @return A list containing the javaDynamodbRangeKeyGsiNames.
     */
    java.util.List<java.lang.String>
        getJavaDynamodbRangeKeyGsiNamesList();
    /**
     * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
     * @return The count of javaDynamodbRangeKeyGsiNames.
     */
    int getJavaDynamodbRangeKeyGsiNamesCount();
    /**
     * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
     * @param index The index of the element to return.
     * @return The javaDynamodbRangeKeyGsiNames at the given index.
     */
    java.lang.String getJavaDynamodbRangeKeyGsiNames(int index);
    /**
     * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the javaDynamodbRangeKeyGsiNames at the given index.
     */
    com.google.protobuf.ByteString
        getJavaDynamodbRangeKeyGsiNamesBytes(int index);
  }
  /**
   * Protobuf type {@code net.moznion.protoc.plugin.dynamodb.FieldOptions}
   */
  public static final class FieldOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.moznion.protoc.plugin.dynamodb.FieldOptions)
      FieldOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FieldOptions.newBuilder() to construct.
    private FieldOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FieldOptions() {
      javaDynamodbAlias_ = "";
      javaDynamodbHashKeyGsiNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      javaDynamodbRangeKeyGsiNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FieldOptions();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FieldOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              javaDynamodbHashKey_ = input.readBool();
              break;
            }
            case 16: {

              javaDynamodbRangeKey_ = input.readBool();
              break;
            }
            case 24: {

              javaDynamodbIgnore_ = input.readBool();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              javaDynamodbAlias_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                javaDynamodbHashKeyGsiNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              javaDynamodbHashKeyGsiNames_.add(s);
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                javaDynamodbRangeKeyGsiNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              javaDynamodbRangeKeyGsiNames_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          javaDynamodbHashKeyGsiNames_ = javaDynamodbHashKeyGsiNames_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          javaDynamodbRangeKeyGsiNames_ = javaDynamodbRangeKeyGsiNames_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.moznion.protoc.plugin.dynamodb.OptionsProto.internal_static_net_moznion_protoc_plugin_dynamodb_FieldOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.moznion.protoc.plugin.dynamodb.OptionsProto.internal_static_net_moznion_protoc_plugin_dynamodb_FieldOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions.class, net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions.Builder.class);
    }

    public static final int JAVA_DYNAMODB_HASH_KEY_FIELD_NUMBER = 1;
    private boolean javaDynamodbHashKey_;
    /**
     * <code>bool java_dynamodb_hash_key = 1;</code>
     * @return The javaDynamodbHashKey.
     */
    @java.lang.Override
    public boolean getJavaDynamodbHashKey() {
      return javaDynamodbHashKey_;
    }

    public static final int JAVA_DYNAMODB_RANGE_KEY_FIELD_NUMBER = 2;
    private boolean javaDynamodbRangeKey_;
    /**
     * <code>bool java_dynamodb_range_key = 2;</code>
     * @return The javaDynamodbRangeKey.
     */
    @java.lang.Override
    public boolean getJavaDynamodbRangeKey() {
      return javaDynamodbRangeKey_;
    }

    public static final int JAVA_DYNAMODB_IGNORE_FIELD_NUMBER = 3;
    private boolean javaDynamodbIgnore_;
    /**
     * <code>bool java_dynamodb_ignore = 3;</code>
     * @return The javaDynamodbIgnore.
     */
    @java.lang.Override
    public boolean getJavaDynamodbIgnore() {
      return javaDynamodbIgnore_;
    }

    public static final int JAVA_DYNAMODB_ALIAS_FIELD_NUMBER = 4;
    private volatile java.lang.Object javaDynamodbAlias_;
    /**
     * <code>string java_dynamodb_alias = 4;</code>
     * @return The javaDynamodbAlias.
     */
    @java.lang.Override
    public java.lang.String getJavaDynamodbAlias() {
      java.lang.Object ref = javaDynamodbAlias_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        javaDynamodbAlias_ = s;
        return s;
      }
    }
    /**
     * <code>string java_dynamodb_alias = 4;</code>
     * @return The bytes for javaDynamodbAlias.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJavaDynamodbAliasBytes() {
      java.lang.Object ref = javaDynamodbAlias_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        javaDynamodbAlias_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JAVA_DYNAMODB_HASH_KEY_GSI_NAMES_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList javaDynamodbHashKeyGsiNames_;
    /**
     * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
     * @return A list containing the javaDynamodbHashKeyGsiNames.
     */
    public com.google.protobuf.ProtocolStringList
        getJavaDynamodbHashKeyGsiNamesList() {
      return javaDynamodbHashKeyGsiNames_;
    }
    /**
     * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
     * @return The count of javaDynamodbHashKeyGsiNames.
     */
    public int getJavaDynamodbHashKeyGsiNamesCount() {
      return javaDynamodbHashKeyGsiNames_.size();
    }
    /**
     * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
     * @param index The index of the element to return.
     * @return The javaDynamodbHashKeyGsiNames at the given index.
     */
    public java.lang.String getJavaDynamodbHashKeyGsiNames(int index) {
      return javaDynamodbHashKeyGsiNames_.get(index);
    }
    /**
     * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the javaDynamodbHashKeyGsiNames at the given index.
     */
    public com.google.protobuf.ByteString
        getJavaDynamodbHashKeyGsiNamesBytes(int index) {
      return javaDynamodbHashKeyGsiNames_.getByteString(index);
    }

    public static final int JAVA_DYNAMODB_RANGE_KEY_GSI_NAMES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList javaDynamodbRangeKeyGsiNames_;
    /**
     * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
     * @return A list containing the javaDynamodbRangeKeyGsiNames.
     */
    public com.google.protobuf.ProtocolStringList
        getJavaDynamodbRangeKeyGsiNamesList() {
      return javaDynamodbRangeKeyGsiNames_;
    }
    /**
     * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
     * @return The count of javaDynamodbRangeKeyGsiNames.
     */
    public int getJavaDynamodbRangeKeyGsiNamesCount() {
      return javaDynamodbRangeKeyGsiNames_.size();
    }
    /**
     * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
     * @param index The index of the element to return.
     * @return The javaDynamodbRangeKeyGsiNames at the given index.
     */
    public java.lang.String getJavaDynamodbRangeKeyGsiNames(int index) {
      return javaDynamodbRangeKeyGsiNames_.get(index);
    }
    /**
     * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the javaDynamodbRangeKeyGsiNames at the given index.
     */
    public com.google.protobuf.ByteString
        getJavaDynamodbRangeKeyGsiNamesBytes(int index) {
      return javaDynamodbRangeKeyGsiNames_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (javaDynamodbHashKey_ != false) {
        output.writeBool(1, javaDynamodbHashKey_);
      }
      if (javaDynamodbRangeKey_ != false) {
        output.writeBool(2, javaDynamodbRangeKey_);
      }
      if (javaDynamodbIgnore_ != false) {
        output.writeBool(3, javaDynamodbIgnore_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(javaDynamodbAlias_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, javaDynamodbAlias_);
      }
      for (int i = 0; i < javaDynamodbHashKeyGsiNames_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, javaDynamodbHashKeyGsiNames_.getRaw(i));
      }
      for (int i = 0; i < javaDynamodbRangeKeyGsiNames_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, javaDynamodbRangeKeyGsiNames_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (javaDynamodbHashKey_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, javaDynamodbHashKey_);
      }
      if (javaDynamodbRangeKey_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, javaDynamodbRangeKey_);
      }
      if (javaDynamodbIgnore_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, javaDynamodbIgnore_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(javaDynamodbAlias_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, javaDynamodbAlias_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < javaDynamodbHashKeyGsiNames_.size(); i++) {
          dataSize += computeStringSizeNoTag(javaDynamodbHashKeyGsiNames_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getJavaDynamodbHashKeyGsiNamesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < javaDynamodbRangeKeyGsiNames_.size(); i++) {
          dataSize += computeStringSizeNoTag(javaDynamodbRangeKeyGsiNames_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getJavaDynamodbRangeKeyGsiNamesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions)) {
        return super.equals(obj);
      }
      net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions other = (net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions) obj;

      if (getJavaDynamodbHashKey()
          != other.getJavaDynamodbHashKey()) return false;
      if (getJavaDynamodbRangeKey()
          != other.getJavaDynamodbRangeKey()) return false;
      if (getJavaDynamodbIgnore()
          != other.getJavaDynamodbIgnore()) return false;
      if (!getJavaDynamodbAlias()
          .equals(other.getJavaDynamodbAlias())) return false;
      if (!getJavaDynamodbHashKeyGsiNamesList()
          .equals(other.getJavaDynamodbHashKeyGsiNamesList())) return false;
      if (!getJavaDynamodbRangeKeyGsiNamesList()
          .equals(other.getJavaDynamodbRangeKeyGsiNamesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JAVA_DYNAMODB_HASH_KEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getJavaDynamodbHashKey());
      hash = (37 * hash) + JAVA_DYNAMODB_RANGE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getJavaDynamodbRangeKey());
      hash = (37 * hash) + JAVA_DYNAMODB_IGNORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getJavaDynamodbIgnore());
      hash = (37 * hash) + JAVA_DYNAMODB_ALIAS_FIELD_NUMBER;
      hash = (53 * hash) + getJavaDynamodbAlias().hashCode();
      if (getJavaDynamodbHashKeyGsiNamesCount() > 0) {
        hash = (37 * hash) + JAVA_DYNAMODB_HASH_KEY_GSI_NAMES_FIELD_NUMBER;
        hash = (53 * hash) + getJavaDynamodbHashKeyGsiNamesList().hashCode();
      }
      if (getJavaDynamodbRangeKeyGsiNamesCount() > 0) {
        hash = (37 * hash) + JAVA_DYNAMODB_RANGE_KEY_GSI_NAMES_FIELD_NUMBER;
        hash = (53 * hash) + getJavaDynamodbRangeKeyGsiNamesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.moznion.protoc.plugin.dynamodb.FieldOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.moznion.protoc.plugin.dynamodb.FieldOptions)
        net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.moznion.protoc.plugin.dynamodb.OptionsProto.internal_static_net_moznion_protoc_plugin_dynamodb_FieldOptions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.moznion.protoc.plugin.dynamodb.OptionsProto.internal_static_net_moznion_protoc_plugin_dynamodb_FieldOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions.class, net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions.Builder.class);
      }

      // Construct using net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        javaDynamodbHashKey_ = false;

        javaDynamodbRangeKey_ = false;

        javaDynamodbIgnore_ = false;

        javaDynamodbAlias_ = "";

        javaDynamodbHashKeyGsiNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        javaDynamodbRangeKeyGsiNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.moznion.protoc.plugin.dynamodb.OptionsProto.internal_static_net_moznion_protoc_plugin_dynamodb_FieldOptions_descriptor;
      }

      @java.lang.Override
      public net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions getDefaultInstanceForType() {
        return net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions.getDefaultInstance();
      }

      @java.lang.Override
      public net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions build() {
        net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions buildPartial() {
        net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions result = new net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions(this);
        int from_bitField0_ = bitField0_;
        result.javaDynamodbHashKey_ = javaDynamodbHashKey_;
        result.javaDynamodbRangeKey_ = javaDynamodbRangeKey_;
        result.javaDynamodbIgnore_ = javaDynamodbIgnore_;
        result.javaDynamodbAlias_ = javaDynamodbAlias_;
        if (((bitField0_ & 0x00000001) != 0)) {
          javaDynamodbHashKeyGsiNames_ = javaDynamodbHashKeyGsiNames_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.javaDynamodbHashKeyGsiNames_ = javaDynamodbHashKeyGsiNames_;
        if (((bitField0_ & 0x00000002) != 0)) {
          javaDynamodbRangeKeyGsiNames_ = javaDynamodbRangeKeyGsiNames_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.javaDynamodbRangeKeyGsiNames_ = javaDynamodbRangeKeyGsiNames_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions) {
          return mergeFrom((net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions other) {
        if (other == net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions.getDefaultInstance()) return this;
        if (other.getJavaDynamodbHashKey() != false) {
          setJavaDynamodbHashKey(other.getJavaDynamodbHashKey());
        }
        if (other.getJavaDynamodbRangeKey() != false) {
          setJavaDynamodbRangeKey(other.getJavaDynamodbRangeKey());
        }
        if (other.getJavaDynamodbIgnore() != false) {
          setJavaDynamodbIgnore(other.getJavaDynamodbIgnore());
        }
        if (!other.getJavaDynamodbAlias().isEmpty()) {
          javaDynamodbAlias_ = other.javaDynamodbAlias_;
          onChanged();
        }
        if (!other.javaDynamodbHashKeyGsiNames_.isEmpty()) {
          if (javaDynamodbHashKeyGsiNames_.isEmpty()) {
            javaDynamodbHashKeyGsiNames_ = other.javaDynamodbHashKeyGsiNames_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureJavaDynamodbHashKeyGsiNamesIsMutable();
            javaDynamodbHashKeyGsiNames_.addAll(other.javaDynamodbHashKeyGsiNames_);
          }
          onChanged();
        }
        if (!other.javaDynamodbRangeKeyGsiNames_.isEmpty()) {
          if (javaDynamodbRangeKeyGsiNames_.isEmpty()) {
            javaDynamodbRangeKeyGsiNames_ = other.javaDynamodbRangeKeyGsiNames_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureJavaDynamodbRangeKeyGsiNamesIsMutable();
            javaDynamodbRangeKeyGsiNames_.addAll(other.javaDynamodbRangeKeyGsiNames_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean javaDynamodbHashKey_ ;
      /**
       * <code>bool java_dynamodb_hash_key = 1;</code>
       * @return The javaDynamodbHashKey.
       */
      @java.lang.Override
      public boolean getJavaDynamodbHashKey() {
        return javaDynamodbHashKey_;
      }
      /**
       * <code>bool java_dynamodb_hash_key = 1;</code>
       * @param value The javaDynamodbHashKey to set.
       * @return This builder for chaining.
       */
      public Builder setJavaDynamodbHashKey(boolean value) {
        
        javaDynamodbHashKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool java_dynamodb_hash_key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearJavaDynamodbHashKey() {
        
        javaDynamodbHashKey_ = false;
        onChanged();
        return this;
      }

      private boolean javaDynamodbRangeKey_ ;
      /**
       * <code>bool java_dynamodb_range_key = 2;</code>
       * @return The javaDynamodbRangeKey.
       */
      @java.lang.Override
      public boolean getJavaDynamodbRangeKey() {
        return javaDynamodbRangeKey_;
      }
      /**
       * <code>bool java_dynamodb_range_key = 2;</code>
       * @param value The javaDynamodbRangeKey to set.
       * @return This builder for chaining.
       */
      public Builder setJavaDynamodbRangeKey(boolean value) {
        
        javaDynamodbRangeKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool java_dynamodb_range_key = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearJavaDynamodbRangeKey() {
        
        javaDynamodbRangeKey_ = false;
        onChanged();
        return this;
      }

      private boolean javaDynamodbIgnore_ ;
      /**
       * <code>bool java_dynamodb_ignore = 3;</code>
       * @return The javaDynamodbIgnore.
       */
      @java.lang.Override
      public boolean getJavaDynamodbIgnore() {
        return javaDynamodbIgnore_;
      }
      /**
       * <code>bool java_dynamodb_ignore = 3;</code>
       * @param value The javaDynamodbIgnore to set.
       * @return This builder for chaining.
       */
      public Builder setJavaDynamodbIgnore(boolean value) {
        
        javaDynamodbIgnore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool java_dynamodb_ignore = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearJavaDynamodbIgnore() {
        
        javaDynamodbIgnore_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object javaDynamodbAlias_ = "";
      /**
       * <code>string java_dynamodb_alias = 4;</code>
       * @return The javaDynamodbAlias.
       */
      public java.lang.String getJavaDynamodbAlias() {
        java.lang.Object ref = javaDynamodbAlias_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          javaDynamodbAlias_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string java_dynamodb_alias = 4;</code>
       * @return The bytes for javaDynamodbAlias.
       */
      public com.google.protobuf.ByteString
          getJavaDynamodbAliasBytes() {
        java.lang.Object ref = javaDynamodbAlias_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          javaDynamodbAlias_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string java_dynamodb_alias = 4;</code>
       * @param value The javaDynamodbAlias to set.
       * @return This builder for chaining.
       */
      public Builder setJavaDynamodbAlias(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        javaDynamodbAlias_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string java_dynamodb_alias = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearJavaDynamodbAlias() {
        
        javaDynamodbAlias_ = getDefaultInstance().getJavaDynamodbAlias();
        onChanged();
        return this;
      }
      /**
       * <code>string java_dynamodb_alias = 4;</code>
       * @param value The bytes for javaDynamodbAlias to set.
       * @return This builder for chaining.
       */
      public Builder setJavaDynamodbAliasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        javaDynamodbAlias_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList javaDynamodbHashKeyGsiNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureJavaDynamodbHashKeyGsiNamesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          javaDynamodbHashKeyGsiNames_ = new com.google.protobuf.LazyStringArrayList(javaDynamodbHashKeyGsiNames_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
       * @return A list containing the javaDynamodbHashKeyGsiNames.
       */
      public com.google.protobuf.ProtocolStringList
          getJavaDynamodbHashKeyGsiNamesList() {
        return javaDynamodbHashKeyGsiNames_.getUnmodifiableView();
      }
      /**
       * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
       * @return The count of javaDynamodbHashKeyGsiNames.
       */
      public int getJavaDynamodbHashKeyGsiNamesCount() {
        return javaDynamodbHashKeyGsiNames_.size();
      }
      /**
       * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
       * @param index The index of the element to return.
       * @return The javaDynamodbHashKeyGsiNames at the given index.
       */
      public java.lang.String getJavaDynamodbHashKeyGsiNames(int index) {
        return javaDynamodbHashKeyGsiNames_.get(index);
      }
      /**
       * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the javaDynamodbHashKeyGsiNames at the given index.
       */
      public com.google.protobuf.ByteString
          getJavaDynamodbHashKeyGsiNamesBytes(int index) {
        return javaDynamodbHashKeyGsiNames_.getByteString(index);
      }
      /**
       * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
       * @param index The index to set the value at.
       * @param value The javaDynamodbHashKeyGsiNames to set.
       * @return This builder for chaining.
       */
      public Builder setJavaDynamodbHashKeyGsiNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureJavaDynamodbHashKeyGsiNamesIsMutable();
        javaDynamodbHashKeyGsiNames_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
       * @param value The javaDynamodbHashKeyGsiNames to add.
       * @return This builder for chaining.
       */
      public Builder addJavaDynamodbHashKeyGsiNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureJavaDynamodbHashKeyGsiNamesIsMutable();
        javaDynamodbHashKeyGsiNames_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
       * @param values The javaDynamodbHashKeyGsiNames to add.
       * @return This builder for chaining.
       */
      public Builder addAllJavaDynamodbHashKeyGsiNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureJavaDynamodbHashKeyGsiNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, javaDynamodbHashKeyGsiNames_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearJavaDynamodbHashKeyGsiNames() {
        javaDynamodbHashKeyGsiNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string java_dynamodb_hash_key_gsi_names = 5;</code>
       * @param value The bytes of the javaDynamodbHashKeyGsiNames to add.
       * @return This builder for chaining.
       */
      public Builder addJavaDynamodbHashKeyGsiNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureJavaDynamodbHashKeyGsiNamesIsMutable();
        javaDynamodbHashKeyGsiNames_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList javaDynamodbRangeKeyGsiNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureJavaDynamodbRangeKeyGsiNamesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          javaDynamodbRangeKeyGsiNames_ = new com.google.protobuf.LazyStringArrayList(javaDynamodbRangeKeyGsiNames_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
       * @return A list containing the javaDynamodbRangeKeyGsiNames.
       */
      public com.google.protobuf.ProtocolStringList
          getJavaDynamodbRangeKeyGsiNamesList() {
        return javaDynamodbRangeKeyGsiNames_.getUnmodifiableView();
      }
      /**
       * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
       * @return The count of javaDynamodbRangeKeyGsiNames.
       */
      public int getJavaDynamodbRangeKeyGsiNamesCount() {
        return javaDynamodbRangeKeyGsiNames_.size();
      }
      /**
       * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
       * @param index The index of the element to return.
       * @return The javaDynamodbRangeKeyGsiNames at the given index.
       */
      public java.lang.String getJavaDynamodbRangeKeyGsiNames(int index) {
        return javaDynamodbRangeKeyGsiNames_.get(index);
      }
      /**
       * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
       * @param index The index of the value to return.
       * @return The bytes of the javaDynamodbRangeKeyGsiNames at the given index.
       */
      public com.google.protobuf.ByteString
          getJavaDynamodbRangeKeyGsiNamesBytes(int index) {
        return javaDynamodbRangeKeyGsiNames_.getByteString(index);
      }
      /**
       * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
       * @param index The index to set the value at.
       * @param value The javaDynamodbRangeKeyGsiNames to set.
       * @return This builder for chaining.
       */
      public Builder setJavaDynamodbRangeKeyGsiNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureJavaDynamodbRangeKeyGsiNamesIsMutable();
        javaDynamodbRangeKeyGsiNames_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
       * @param value The javaDynamodbRangeKeyGsiNames to add.
       * @return This builder for chaining.
       */
      public Builder addJavaDynamodbRangeKeyGsiNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureJavaDynamodbRangeKeyGsiNamesIsMutable();
        javaDynamodbRangeKeyGsiNames_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
       * @param values The javaDynamodbRangeKeyGsiNames to add.
       * @return This builder for chaining.
       */
      public Builder addAllJavaDynamodbRangeKeyGsiNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureJavaDynamodbRangeKeyGsiNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, javaDynamodbRangeKeyGsiNames_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearJavaDynamodbRangeKeyGsiNames() {
        javaDynamodbRangeKeyGsiNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string java_dynamodb_range_key_gsi_names = 6;</code>
       * @param value The bytes of the javaDynamodbRangeKeyGsiNames to add.
       * @return This builder for chaining.
       */
      public Builder addJavaDynamodbRangeKeyGsiNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureJavaDynamodbRangeKeyGsiNamesIsMutable();
        javaDynamodbRangeKeyGsiNames_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.moznion.protoc.plugin.dynamodb.FieldOptions)
    }

    // @@protoc_insertion_point(class_scope:net.moznion.protoc.plugin.dynamodb.FieldOptions)
    private static final net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions();
    }

    public static net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FieldOptions>
        PARSER = new com.google.protobuf.AbstractParser<FieldOptions>() {
      @java.lang.Override
      public FieldOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FieldOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FieldOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FieldOptions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int FILEOPT_FIELD_NUMBER = 50000;
  /**
   * <pre>
   * TODO be unique number
   * </pre>
   *
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions> fileopt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions.class,
        net.moznion.protoc.plugin.dynamodb.OptionsProto.FileOptions.getDefaultInstance());
  public static final int FIELDOPT_FIELD_NUMBER = 50001;
  /**
   * <pre>
   * TODO be unique number
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions> fieldopt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions.class,
        net.moznion.protoc.plugin.dynamodb.OptionsProto.FieldOptions.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_moznion_protoc_plugin_dynamodb_FileOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_moznion_protoc_plugin_dynamodb_FileOptions_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_moznion_protoc_plugin_dynamodb_FieldOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_moznion_protoc_plugin_dynamodb_FieldOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024protos/options.proto\022\"net.moznion.prot" +
      "oc.plugin.dynamodb\032 google/protobuf/desc" +
      "riptor.proto\"/\n\013FileOptions\022 \n\030java_dyna" +
      "modb_table_name\030\001 \001(\t\"\337\001\n\014FieldOptions\022\036" +
      "\n\026java_dynamodb_hash_key\030\001 \001(\010\022\037\n\027java_d" +
      "ynamodb_range_key\030\002 \001(\010\022\034\n\024java_dynamodb" +
      "_ignore\030\003 \001(\010\022\033\n\023java_dynamodb_alias\030\004 \001" +
      "(\t\022(\n java_dynamodb_hash_key_gsi_names\030\005" +
      " \003(\t\022)\n!java_dynamodb_range_key_gsi_name" +
      "s\030\006 \003(\t:`\n\007fileopt\022\034.google.protobuf.Fil" +
      "eOptions\030\320\206\003 \001(\0132/.net.moznion.protoc.pl" +
      "ugin.dynamodb.FileOptions:c\n\010fieldopt\022\035." +
      "google.protobuf.FieldOptions\030\321\206\003 \001(\01320.n" +
      "et.moznion.protoc.plugin.dynamodb.FieldO" +
      "ptionsB2\n\"net.moznion.protoc.plugin.dyna" +
      "modbB\014OptionsProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_net_moznion_protoc_plugin_dynamodb_FileOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_moznion_protoc_plugin_dynamodb_FileOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_moznion_protoc_plugin_dynamodb_FileOptions_descriptor,
        new java.lang.String[] { "JavaDynamodbTableName", });
    internal_static_net_moznion_protoc_plugin_dynamodb_FieldOptions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_moznion_protoc_plugin_dynamodb_FieldOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_moznion_protoc_plugin_dynamodb_FieldOptions_descriptor,
        new java.lang.String[] { "JavaDynamodbHashKey", "JavaDynamodbRangeKey", "JavaDynamodbIgnore", "JavaDynamodbAlias", "JavaDynamodbHashKeyGsiNames", "JavaDynamodbRangeKeyGsiNames", });
    fileopt.internalInit(descriptor.getExtensions().get(0));
    fieldopt.internalInit(descriptor.getExtensions().get(1));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
